[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-frame"

version = "0.4.2"

description = "FastAPI Frame (774style)"
authors = [
  { name="Kengo NAKADA", email="kengo.nakada@email.com" }
]
readme = "README.md"
requires-python = ">=3.10"  # 必要に応じて更新
dependencies = [
"fastapi",
"pytango",
"uvicorn",
"pydantic",
"sphinx",
"myst-parser",
"sphinx-autobuild",
"sphinx-rtd-theme",
"sphinxcontrib-napoleon",
"linkify-it-py"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["fastapi*"]

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
