#!/usr/bin/env python
from ese774_frame.models.api_spec import ApiSpec

from server.models import (
    AddRequest,
    EchoRequest,
    SumListRequest,
    MixRequest,
    TupleRequest,
    DictRequest,
    MaybeRequest,
    SetNameRequest,
)

# response_model は None（pydanticはI/F定義のみ。戻り値は純粋Pythonを透過）
simple_api_spec = [
    ApiSpec(
        name="ping",
        object_name="simple",
        request_model=None,
        response_model=None,
        method="post",
        summary="ping",
        description="return 'pong'",
    ),
    ApiSpec(
        name="add",
        object_name="simple",
        request_model=AddRequest,
        response_model=None,
        method="post",
        summary="add",
        description="a + b",
    ),
    ApiSpec(
        name="echo",
        object_name="simple",
        request_model=EchoRequest,
        response_model=None,
        method="post",
        summary="echo",
        description="echo msg",
    ),
    ApiSpec(
        name="sum_list",
        object_name="simple",
        request_model=SumListRequest,
        response_model=None,
        method="post",
        summary="sum_list",
        description="sum(values)",
    ),
    ApiSpec(
        name="mix",
        object_name="simple",
        request_model=MixRequest,
        response_model=None,
        method="post",
        summary="mix",
        description="(a+b)*scale",
    ),
    ApiSpec(
        name="make_tuple",
        object_name="simple",
        request_model=TupleRequest,
        response_model=None,
        method="post",
        summary="make_tuple",
        description="return tuple",
    ),
    ApiSpec(
        name="make_dict",
        object_name="simple",
        request_model=DictRequest,
        response_model=None,
        method="post",
        summary="make_dict",
        description="return dict",
    ),
    ApiSpec(
        name="maybe",
        object_name="simple",
        request_model=MaybeRequest,
        response_model=None,
        method="post",
        summary="maybe",
        description="optional return",
    ),
    ApiSpec(
        name="set_name",
        object_name="simple",
        request_model=SetNameRequest,
        response_model=None,
        method="post",
        summary="set_name",
        description="set name",
    ),
    ApiSpec(
        name="get_state",
        object_name="simple",
        request_model=None,
        response_model=None,
        method="post",
        summary="get_state",
        description="state dict",
    ),
    ApiSpec(
        name="name",
        object_name="simple",
        request_model=None,
        response_model=None,
        method="post",
        summary="name (property)",
        description="property access",
    ),
]
